version: "3.9"

services:

  db_dev:
    container_name: "db_dev"
    image: postgres:14.1-alpine
    volumes:
      - ./pg_db_dev:/var/lib/postgresql/data/
    restart: always
    environment:
      - TZ=Etc/UTC
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - net_dev

  pgadmin:
    container_name: "pgadmin"
    image: dpage/pgadmin4
    environment:
      - TZ=Etc/UTC
      - PGADMIN_DEFAULT_EMAIL=user@user.ru
      - PGADMIN_DEFAULT_PASSWORD=qazxsw123
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_LISTEN_PORT=5555
    ports:
      - "5555:5555"
    depends_on:
      - db_dev
    networks:
      - net_dev

networks:
  net_dev:
    driver: bridge
