"""Fist

Revision ID: 57c7b31c2df1
Revises: 
Create Date: 2023-03-25 16:18:02.982925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "57c7b31c2df1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("surname", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("user_pkey")),
        sa.UniqueConstraint("email", name=op.f("user_email_key")),
    )
    op.create_index(op.f("user_created_at_idx"), "user", ["created_at"], unique=False)
    op.create_index(op.f("user_id_idx"), "user", ["id"], unique=False)
    op.create_table(
        "user_notification",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("message", sa.String(length=512), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name=op.f("user_notification_user_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("user_notification_pkey")),
    )
    op.create_index(op.f("user_notification_created_at_idx"), "user_notification", ["created_at"], unique=False)
    op.create_index(op.f("user_notification_id_idx"), "user_notification", ["id"], unique=False)
    op.create_index(op.f("user_notification_user_id_idx"), "user_notification", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("user_notification_user_id_idx"), table_name="user_notification")
    op.drop_index(op.f("user_notification_id_idx"), table_name="user_notification")
    op.drop_index(op.f("user_notification_created_at_idx"), table_name="user_notification")
    op.drop_table("user_notification")
    op.drop_index(op.f("user_id_idx"), table_name="user")
    op.drop_index(op.f("user_created_at_idx"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
